/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fay_qr;

import java.awt.Color;
import java.awt.Image;
import static javax.swing.Box.createHorizontalGlue;
import javax.swing.ImageIcon;

/**
 *
 * @author Harlen
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        
        
         //icono
        setIconImage(new ImageIcon(getClass().getResource("/img/icono_fayqr.png")).getImage());
        
        //poner la ventana en el centro
        this.setLocationRelativeTo(null);
        
        logo();
        
        jMenu6.add(createHorizontalGlue());
    }

   
    
    
    
    private void logo(){//METODO DE IMAGEN 
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/img/qr_logo.png"));//OBJETO del icono
    Image imagen = icono.getImage();//guardo la imagen original
    //redimencionar la imagen
    ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(160,160,Image.SCALE_SMOOTH));
    lblLogo.setIcon(iconoEscalado);//pongo la imagen en la label
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBienvenida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAlumno = new javax.swing.JMenu();
        miRegistrarAlumno = new javax.swing.JMenuItem();
        mnEvento = new javax.swing.JMenu();
        miRegistrarEvento = new javax.swing.JMenuItem();
        mnAsistencias = new javax.swing.JMenu();
        miVer = new javax.swing.JMenuItem();
        mnOrganizador = new javax.swing.JMenu();
        miRegistrarOrg = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnAcercade = new javax.swing.JMenu();
        mnItemCreador = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();
        mnVolverL = new javax.swing.JMenuItem();
        mnCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBienvenida.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 109, 214));
        jLabel1.setText("Bienvenid@");

        jPanel1.setBackground(new java.awt.Color(71, 181, 244));

        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("¡Hola! Disfruta de esta experiencia");

        javax.swing.GroupLayout pnlBienvenidaLayout = new javax.swing.GroupLayout(pnlBienvenida);
        pnlBienvenida.setLayout(pnlBienvenidaLayout);
        pnlBienvenidaLayout.setHorizontalGroup(
            pnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBienvenidaLayout.createSequentialGroup()
                .addGroup(pnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBienvenidaLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(pnlBienvenidaLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBienvenidaLayout.setVerticalGroup(
            pnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBienvenidaLayout.createSequentialGroup()
                .addGroup(pnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBienvenidaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 50));

        mnAlumno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnAlumno.setText("Alumno");
        mnAlumno.setBorderPainted(false);
        mnAlumno.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        mnAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnAlumno.setMinimumSize(new java.awt.Dimension(120, 30));
        mnAlumno.setPreferredSize(new java.awt.Dimension(75, 27));
        mnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlumnoActionPerformed(evt);
            }
        });

        miRegistrarAlumno.setText("Registrar");
        miRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarAlumnoActionPerformed(evt);
            }
        });
        mnAlumno.add(miRegistrarAlumno);

        jMenuBar1.add(mnAlumno);

        mnEvento.setText("Evento");
        mnEvento.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        mnEvento.setMinimumSize(new java.awt.Dimension(120, 30));

        miRegistrarEvento.setText("Registrar");
        miRegistrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarEventoActionPerformed(evt);
            }
        });
        mnEvento.add(miRegistrarEvento);

        jMenuBar1.add(mnEvento);

        mnAsistencias.setText("Asistencias");
        mnAsistencias.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        mnAsistencias.setMinimumSize(new java.awt.Dimension(120, 30));

        miVer.setText("Ver");
        miVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerActionPerformed(evt);
            }
        });
        mnAsistencias.add(miVer);

        jMenuBar1.add(mnAsistencias);

        mnOrganizador.setText("Organizador");
        mnOrganizador.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        mnOrganizador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnOrganizador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnOrganizador.setPreferredSize(new java.awt.Dimension(120, 30));

        miRegistrarOrg.setText("Registrar");
        miRegistrarOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarOrgActionPerformed(evt);
            }
        });
        mnOrganizador.add(miRegistrarOrg);

        jMenuBar1.add(mnOrganizador);

        jMenu6.setText("|                                                                                                                          |");
        jMenu6.setEnabled(false);
        jMenuBar1.add(jMenu6);

        mnAcercade.setText("Acerca de ...");
        mnAcercade.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        mnAcercade.setHideActionText(true);
        mnAcercade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnAcercade.setMinimumSize(new java.awt.Dimension(120, 30));

        mnItemCreador.setText("Creadores");
        mnItemCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCreadorActionPerformed(evt);
            }
        });
        mnAcercade.add(mnItemCreador);

        jMenuBar1.add(mnAcercade);

        mnSalir.setText("Salir");
        mnSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        mnSalir.setHideActionText(true);
        mnSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnSalir.setMinimumSize(new java.awt.Dimension(120, 30));
        mnSalir.setPreferredSize(new java.awt.Dimension(50, 50));

        mnVolverL.setText("Cerrar Sesión");
        mnVolverL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVolverLActionPerformed(evt);
            }
        });
        mnSalir.add(mnVolverL);

        mnCerrar.setText("Cerrar");
        mnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarActionPerformed(evt);
            }
        });
        mnSalir.add(mnCerrar);

        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnAlumnoActionPerformed

    private void miRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarAlumnoActionPerformed
        // TODO add your handling code here:        
        frmAlumno a =new  frmAlumno();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miRegistrarAlumnoActionPerformed

    private void miRegistrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarEventoActionPerformed
        // TODO add your handling code here:
        frmEvento re =new  frmEvento();
        re.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miRegistrarEventoActionPerformed

    private void miVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerActionPerformed
        // TODO add your handling code here:
        frmAsistensias asis =new  frmAsistensias();
        asis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miVerActionPerformed

    private void miRegistrarOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarOrgActionPerformed
        // TODO add your handling code here:
        frmOrganizador org =new  frmOrganizador();
        org.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miRegistrarOrgActionPerformed

    private void mnVolverLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVolverLActionPerformed
        // TODO add your handling code here:
        frmLogin login =new  frmLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnVolverLActionPerformed

    private void mnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnCerrarActionPerformed

    private void mnItemCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCreadorActionPerformed
        // TODO add your handling code here:
        frmCreadores cr =new  frmCreadores();
        cr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemCreadorActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenuItem miRegistrarAlumno;
    private javax.swing.JMenuItem miRegistrarEvento;
    private javax.swing.JMenuItem miRegistrarOrg;
    private javax.swing.JMenuItem miVer;
    private javax.swing.JMenu mnAcercade;
    private javax.swing.JMenu mnAlumno;
    private javax.swing.JMenu mnAsistencias;
    private javax.swing.JMenuItem mnCerrar;
    private javax.swing.JMenu mnEvento;
    private javax.swing.JMenuItem mnItemCreador;
    private javax.swing.JMenu mnOrganizador;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnVolverL;
    private javax.swing.JPanel pnlBienvenida;
    // End of variables declaration//GEN-END:variables
}
